on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: ~

name: Import

jobs:
  recent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: data/wiki-meta-cache.yaml
          key: wiki-meta-cache
      - run: |
          npm install
          npm run recent
          npm run schema
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Import recent changes from PCGamingWiki
          commit_author: GitHub Actions <actions@github.com>
