on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: ~

name: Import

jobs:
  recent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v3
        with:
          path: data/wiki-meta-cache.yaml
          key: wiki-meta-cache-v2-${{ github.run_id }}
          restore-keys: |
            wiki-meta-cache-v2
      - name: Python dependencies
        run: pip install "steam[client]"
      - run: cargo build
      - run: cargo run -- bulk --recent-changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Import recent changes from PCGamingWiki
          commit_author: GitHub Actions <actions@github.com>
