on:
  workflow_dispatch:
    inputs:
      timestamp:
        description: 'Timestamp to inject into wiki-meta-cache.yaml. Example: 2022-10-30T19:37:23.138Z'
        required: true
        type: string

name: Set lastCheckedRecentChanges

jobs:
  set-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v3
        with:
          path: data/wiki-meta-cache.yaml
          key: wiki-meta-cache-${{ github.run_id }}
          restore-keys: |
            wiki-meta-cache
      - run: |
          echo "lastCheckedRecentChanges: '$TIMESTAMP'" > data/wiki-meta-cache.yaml
        env:
          TIMESTAMP: ${{ inputs.timestamp }}
